version: '3.5'

services:
  app:
    build: .
    container_name: deteccao-incidentes-telegram
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/deteccao-incidentes
    depends_on:
      - db

  db:
    image: postgres:alpine
    container_name: deteccao-incidentes-telegram-postgres
    restart: always
    tty: true
    ports:
      - "5433:5433"
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: deteccao-incidentes

volumes:
  dbdata: